# Amalia project-wide Gradle settings.

# JVM arguments for the Gradle daemon.
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Run Gradle with parallel & cached configuration when possible.
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true

# Namespaced R classes — smaller R classes.
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official
