#!/usr/bin/env python3
# Добавляет недостающие строки во все локали.
import io, os

BASE = 'app/src/main/res'

KEYS = [
    "assistant_tools_more", "assistant_actions_title", "assistant_actions_ok",
    "assistant_actions_partial", "assistant_context_compressed", "assistant_action_failed",
    "assistant_mic_denied", "assistant_generic_error", "suggestion_check", "suggestion_undo",
    "history_context_summary", "history_compressed_marker", "history_actions_count",
    "appearance_motif", "appearance_motif_desc", "appearance_motif_density",
    "motif_off", "motif_auto", "motif_sakura", "motif_maple", "motif_firefly",
    "motif_snow", "motif_stars", "privacy_resume_session", "privacy_resume_session_desc",
]

T = {
 'values': {  # русский — язык по умолчанию
  "assistant_tools_more": "%1$d ещё",
  "assistant_actions_title": "Что сделано",
  "assistant_actions_ok": "Выполнено: %1$d",
  "assistant_actions_partial": "Выполнено: %1$d · с ошибкой: %2$d",
  "assistant_context_compressed": "контекст сжат",
  "assistant_action_failed": "не получилось",
  "assistant_mic_denied": "Без доступа к микрофону я не слышу. Разреши доступ в настройках приложения.",
  "assistant_generic_error": "Что-то пошло не так. Попробуй ещё раз.",
  "suggestion_check": "Проверь результат",
  "suggestion_undo": "Отмени",
  "history_context_summary": "Резюме контекста",
  "history_compressed_marker": "Начало диалога Амалия помнит пересказом, а не дословно",
  "history_actions_count": "действий: %1$d",
  "appearance_motif": "Декор фона",
  "appearance_motif_desc": "Лепестки, листья, снег, звёзды или светлячки — в такт времени суток",
  "appearance_motif_density": "Густота декораций",
  "motif_off": "Без декора",
  "motif_auto": "По времени",
  "motif_sakura": "Сакура",
  "motif_maple": "Листопад",
  "motif_firefly": "Светлячки",
  "motif_snow": "Снег",
  "motif_stars": "Звёзды",
  "privacy_resume_session": "Продолжать последний диалог",
  "privacy_resume_session_desc": "После перезапуска Амалия помнит контекст разговора",
 },
 'values-en': {
  "assistant_tools_more": "%1$d more",
  "assistant_actions_title": "What was done",
  "assistant_actions_ok": "Done: %1$d",
  "assistant_actions_partial": "Done: %1$d · failed: %2$d",
  "assistant_context_compressed": "context compressed",
  "assistant_action_failed": "didn't work",
  "assistant_mic_denied": "Without microphone access I can't hear. Allow it in app settings.",
  "assistant_generic_error": "Something went wrong. Try again.",
  "suggestion_check": "Check the result",
  "suggestion_undo": "Undo",
  "history_context_summary": "Context summary",
  "history_compressed_marker": "Amalia remembers the beginning as a summary, not verbatim",
  "history_actions_count": "actions: %1$d",
  "appearance_motif": "Background decor",
  "appearance_motif_desc": "Petals, leaves, snow, stars or fireflies — in step with the time of day",
  "appearance_motif_density": "Decor density",
  "motif_off": "No decor",
  "motif_auto": "By time of day",
  "motif_sakura": "Sakura",
  "motif_maple": "Falling leaves",
  "motif_firefly": "Fireflies",
  "motif_snow": "Snow",
  "motif_stars": "Stars",
  "privacy_resume_session": "Resume the last conversation",
  "privacy_resume_session_desc": "After a restart Amalia keeps the conversation context",
 },
 'values-es': {
  "assistant_tools_more": "%1$d más",
  "assistant_actions_title": "Qué hizo",
  "assistant_actions_ok": "Hecho: %1$d",
  "assistant_actions_partial": "Hecho: %1$d · fallidos: %2$d",
  "assistant_context_compressed": "contexto comprimido",
  "assistant_action_failed": "no funcionó",
  "assistant_mic_denied": "Sin acceso al micrófono no escucho. Permítelo en los ajustes.",
  "assistant_generic_error": "Algo salió mal. Inténtalo de nuevo.",
  "suggestion_check": "Comprueba el resultado",
  "suggestion_undo": "Deshacer",
  "history_context_summary": "Resumen del contexto",
  "history_compressed_marker": "Amalia recuerda el inicio como resumen, no literal",
  "history_actions_count": "acciones: %1$d",
  "appearance_motif": "Decoración del fondo",
  "appearance_motif_desc": "Pétalos, hojas, nieve, estrellas o luciérnagas según la hora",
  "appearance_motif_density": "Densidad de la decoración",
  "motif_off": "Sin decoración",
  "motif_auto": "Según la hora",
  "motif_sakura": "Sakura",
  "motif_maple": "Hojas secas",
  "motif_firefly": "Luciérnagas",
  "motif_snow": "Nieve",
  "motif_stars": "Estrellas",
  "privacy_resume_session": "Continuar la última conversación",
  "privacy_resume_session_desc": "Tras reiniciar, Amalia mantiene el contexto",
 },
 'values-de': {
  "assistant_tools_more": "%1$d weitere",
  "assistant_actions_title": "Was getan wurde",
  "assistant_actions_ok": "Erledigt: %1$d",
  "assistant_actions_partial": "Erledigt: %1$d · fehlerhaft: %2$d",
  "assistant_context_compressed": "Kontext verdichtet",
  "assistant_action_failed": "fehlgeschlagen",
  "assistant_mic_denied": "Ohne Mikrofonzugriff höre ich nichts. Erlaube ihn in den Einstellungen.",
  "assistant_generic_error": "Etwas ist schiefgelaufen. Versuch es erneut.",
  "suggestion_check": "Ergebnis prüfen",
  "suggestion_undo": "Abbrechen",
  "history_context_summary": "Kontextzusammenfassung",
  "history_compressed_marker": "Amalia erinnert den Anfang als Zusammenfassung, nicht wörtlich",
  "history_actions_count": "Aktionen: %1$d",
  "appearance_motif": "Hintergrund-Dekor",
  "appearance_motif_desc": "Blüten, Blätter, Schnee, Sterne oder Glühwürmchen zur Tageszeit",
  "appearance_motif_density": "Dichte des Dekors",
  "motif_off": "Ohne Dekor",
  "motif_auto": "Nach Tageszeit",
  "motif_sakura": "Kirschblüte",
  "motif_maple": "Laubfall",
  "motif_firefly": "Glühwürmchen",
  "motif_snow": "Schnee",
  "motif_stars": "Sterne",
  "privacy_resume_session": "Letzte Unterhaltung fortsetzen",
  "privacy_resume_session_desc": "Nach dem Neustart behält Amalia den Kontext",
 },
 'values-fr': {
  "assistant_tools_more": "%1$d de plus",
  "assistant_actions_title": "Ce qui a été fait",
  "assistant_actions_ok": "Fait : %1$d",
  "assistant_actions_partial": "Fait : %1$d · en échec : %2$d",
  "assistant_context_compressed": "contexte compressé",
  "assistant_action_failed": "échec",
  "assistant_mic_denied": "Sans accès au micro, je n'entends rien. Autorise-le dans les réglages.",
  "assistant_generic_error": "Une erreur est survenue. Réessaie.",
  "suggestion_check": "Vérifier le résultat",
  "suggestion_undo": "Annuler",
  "history_context_summary": "Résumé du contexte",
  "history_compressed_marker": "Amalia retient le début en résumé, pas mot à mot",
  "history_actions_count": "actions : %1$d",
  "appearance_motif": "Décor d'arrière-plan",
  "appearance_motif_desc": "Pétales, feuilles, neige, étoiles ou lucioles selon l'heure",
  "appearance_motif_density": "Densité du décor",
  "motif_off": "Sans décor",
  "motif_auto": "Selon l'heure",
  "motif_sakura": "Sakura",
  "motif_maple": "Feuilles mortes",
  "motif_firefly": "Lucioles",
  "motif_snow": "Neige",
  "motif_stars": "Étoiles",
  "privacy_resume_session": "Reprendre la dernière conversation",
  "privacy_resume_session_desc": "Après un redémarrage, Amalia garde le contexte",
 },
 'values-ar': {
  "assistant_tools_more": "%1$d أخرى",
  "assistant_actions_title": "ما تم تنفيذه",
  "assistant_actions_ok": "تم: %1$d",
  "assistant_actions_partial": "تم: %1$d · فشل: %2$d",
  "assistant_context_compressed": "السياق مضغوط",
  "assistant_action_failed": "لم ينجح",
  "assistant_mic_denied": "بدون إذن الميكروفون لا أسمع. اسمح به في إعدادات التطبيق.",
  "assistant_generic_error": "حدث خطأ ما. حاول مرة أخرى.",
  "suggestion_check": "تحقق من النتيجة",
  "suggestion_undo": "تراجع",
  "history_context_summary": "ملخص السياق",
  "history_compressed_marker": "أماليا تتذكر البداية كملخص، وليست حرفياً",
  "history_actions_count": "إجراءات: %1$d",
  "appearance_motif": "زخرفة الخلفية",
  "appearance_motif_desc": "بتلات أو أوراق أو ثلج أو نجوم أو فراغات مضيئة حسب الوقت",
  "appearance_motif_density": "كثافة الزخرفة",
  "motif_off": "بدون زخرفة",
  "motif_auto": "حسب الوقت",
  "motif_sakura": "بتلات الكرز",
  "motif_maple": "أوراق متساقطة",
  "motif_firefly": "فراغات مضيئة",
  "motif_snow": "ثلج",
  "motif_stars": "نجوم",
  "privacy_resume_session": "متابعة آخر محادثة",
  "privacy_resume_session_desc": "بعد إعادة التشغيل تتذكر أماليا سياق الحديث",
 },
 'values-hi': {
  "assistant_tools_more": "%1$d और",
  "assistant_actions_title": "क्या किया गया",
  "assistant_actions_ok": "पूरा: %1$d",
  "assistant_actions_partial": "पूरा: %1$d · विफल: %2$d",
  "assistant_context_compressed": "संदर्भ संपीड़ित",
  "assistant_action_failed": "नहीं हो सका",
  "assistant_mic_denied": "माइक अनुमति के बिना मैं सुन नहीं सकती। ऐप सेटिंग में अनुमति दें।",
  "assistant_generic_error": "कुछ गड़बड़ हो गई। फिर से कोशिश करो।",
  "suggestion_check": "नतीजा जाँचो",
  "suggestion_undo": "वापस लो",
  "history_context_summary": "संदर्भ सारांश",
  "history_compressed_marker": "अमालिया शुरुआत को सारांश के रूप में याद रखती है, शब्दशः नहीं",
  "history_actions_count": "क्रियाएँ: %1$d",
  "appearance_motif": "पृष्ठभूमि सजावट",
  "appearance_motif_desc": "पंखुड़ियाँ, पत्ते, बर्फ, तारे या जुगनू — समय के साथ",
  "appearance_motif_density": "सजावट की घनत्व",
  "motif_off": "बिना सजावट",
  "motif_auto": "समय अनुसार",
  "motif_sakura": "साकुरा",
  "motif_maple": "गिरते पत्ते",
  "motif_firefly": "जुगनू",
  "motif_snow": "बर्फ",
  "motif_stars": "तारे",
  "privacy_resume_session": "आख़िरी बातचीत जारी रखें",
  "privacy_resume_session_desc": "रीस्टार्ट के बाद अमालिया संदर्भ याद रखती है",
 },
 'values-ja': {
  "assistant_tools_more": "他 %1$d 件",
  "assistant_actions_title": "実行した内容",
  "assistant_actions_ok": "完了: %1$d",
  "assistant_actions_partial": "完了: %1$d · 失敗: %2$d",
  "assistant_context_compressed": "文脈を圧縮中",
  "assistant_action_failed": "うまくいきませんでした",
  "assistant_mic_denied": "マイクの許可がないと聞こえません。アプリ設定で許可してください。",
  "assistant_generic_error": "うまくいきませんでした。もう一度どうぞ。",
  "suggestion_check": "結果を確認",
  "suggestion_undo": "取り消し",
  "history_context_summary": "文脈の要約",
  "history_compressed_marker": "アマリアは冒頭を逐語ではなく要約で覚えています",
  "history_actions_count": "操作: %1$d",
  "appearance_motif": "背景の装飾",
  "appearance_motif_desc": "時刻に応じて花びら・葉・雪・星・ホタル",
  "appearance_motif_density": "装飾の密度",
  "motif_off": "装飾なし",
  "motif_auto": "時刻まかせ",
  "motif_sakura": "桜",
  "motif_maple": "紅葉",
  "motif_firefly": "ホタル",
  "motif_snow": "雪",
  "motif_stars": "星",
  "privacy_resume_session": "前の会話を続ける",
  "privacy_resume_session_desc": "再起動後もアマリアは文脈を覚えている",
 },
 'values-zh': {
  "assistant_tools_more": "还有 %1$d 项",
  "assistant_actions_title": "已完成的操作",
  "assistant_actions_ok": "已完成：%1$d",
  "assistant_actions_partial": "已完成：%1$d · 失败：%2$d",
  "assistant_context_compressed": "上下文已压缩",
  "assistant_action_failed": "没有成功",
  "assistant_mic_denied": "没有麦克风权限我听不到。请在应用设置中允许。",
  "assistant_generic_error": "出错了，再试一次。",
  "suggestion_check": "检查结果",
  "suggestion_undo": "撤销",
  "history_context_summary": "上下文摘要",
  "history_compressed_marker": "阿玛利亚以摘要而非逐字记住对话开头",
  "history_actions_count": "操作：%1$d",
  "appearance_motif": "背景装饰",
  "appearance_motif_desc": "随时段飘落花瓣、落叶、雪、星星或萤火虫",
  "appearance_motif_density": "装饰密度",
  "motif_off": "无装饰",
  "motif_auto": "随时段",
  "motif_sakura": "樱花",
  "motif_maple": "落叶",
  "motif_firefly": "萤火虫",
  "motif_snow": "雪",
  "motif_stars": "星星",
  "privacy_resume_session": "继续上一段对话",
  "privacy_resume_session_desc": "重启后阿玛利亚仍保留对话上下文",
 },
}


def esc(value: str) -> str:
    return (
        value.replace('&', '&amp;')
        .replace('<', '&lt;')
        .replace('>', '&gt;')
        .replace("'", "\\'")
    )


for folder, table in T.items():
    path = os.path.join(BASE, folder, 'strings.xml')
    if not os.path.exists(path):
        print('skip', path)
        continue
    src = io.open(path, encoding='utf-8').read()
    missing = [k for k in KEYS if ('name="%s"' % k) not in src]
    if not missing:
        print('complete', path)
        continue
    # Вставка перед </resources> сегментом с фиксированным порядком ключей.
    lines = ['\n    <!-- === Амалия: действия, контекст, декор фона === -->']
    for key in KEYS:
        if key in missing:
            lines.append('    <string name="%s">%s</string>' % (key, esc(table[key])))
    block = '\n'.join(lines) + '\n'
    idx = src.rindex('</resources>')
    src = src[:idx] + block + src[idx:]
    io.open(path, 'w', encoding='utf-8').write(src)
    print('added %d -> %s' % (len(missing), path))
